# Generated by Django 3.1.4 on 2020-12-16 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_Title', models.CharField(max_length=60)),
                ('Recipe_Ingredients', models.TextField()),
                ('Recipe_Description', models.TextField()),
                ('Recipe_Info', models.TextField()),
                ('Recipe_Img', models.ImageField(upload_to='../recepty/img')),
                ('Recipe_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Recipe_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
