# Generated by Django 2.2.6 on 2020-11-16 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Recipe_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
