# Generated by Django 3.1.4 on 2020-12-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Recipe_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Recipe_Img',
            field=models.ImageField(blank=True, upload_to='../recepty/img'),
        ),
    ]
