# Generated by Django 2.2.6 on 2021-01-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201216_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Recipe_Cat',
            field=models.IntegerField(choices=[(1, 'Snídaně a svačiny'), (2, 'Obědy a večeře'), (3, 'Zdravé mlsání'), (4, 'Polévky'), (5, 'Saláty a přílohy'), (6, 'Nápoje')], default=1),
        ),
    ]
