# Generated by Django 2.2.6 on 2021-01-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_recipe_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Title', models.CharField(max_length=60)),
                ('Cat_Description', models.TextField()),
            ],
        ),
    ]
