# Generated by Django 2.2.6 on 2021-01-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_addcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcat',
            name='Cat_Description',
            field=models.TextField(blank=True),
        ),
    ]
