# Generated by Django 2.2.6 on 2021-01-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210118_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCat',
            new_name='addingCat',
        ),
    ]
