# Generated by Django 2.2.6 on 2021-01-19 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_auto_20210119_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addingCat',
            new_name='Cat',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Cat_Title',
            new_name='Cat_Name',
        ),
        migrations.CreateModel(
            name='Prispevek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('datum_vytvoreni', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_publikace', models.DateTimeField(blank=True, null=True)),
                ('tvurce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
